apiVersion: v2
name: kube-prometheus-stack
description: Prometheus monitoring stack with Grafana and AlertManager
version: 1.0.0
dependencies:
- name: kube-prometheus-stack
  version: 65.1.1
  repository: https://prometheus-community.github.io/helm-charts